config:
    # IDs & paths
    data_id: "real_data"
    model_id: "finetuner_large_1_fp_1"
    models_dir: "/Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/trained_models/Zheming/"
    load_data: True
    
    # Training params
    source: "large"
    network_type: "large"
    iterations: 50
    num_classes: 60
    sigmoid_params: [[1000, 1000], [10000, 2000], [100000, 5000]]
    batch_size: 230
    lr: 0.002597

    # WANDB params
    enable_logging: False
    wandb_project_id: "exp_finetuner_fp"

    # Network params
    num_hidden_layers: 2
    num_neurons: 742

    # Misc
    device: "cuda"