config:
    # IDs & paths
    data_id: "real_data"
    model_id: "finetuner_low_1_fp_1"
    models_dir: "/Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/trained_models/Zheming/"
    load_data: True
    
    # Training params
    source: "low"
    network_type: "low"
    iterations: 50
    num_classes: 60
    sigmoid_params: [[500, 150], [5000, 1000], [10000, 5000]]
    batch_size: 167
    lr: 0.001826

    # WANDB params
    enable_logging: False
    wandb_project_id: "exp_finetuner_fp"

    # Network params
    num_hidden_layers: 1
    num_neurons: 800

    # Misc
    device: "cuda"