wandb_version: 1

data_id:
  desc: null
  value: real_data
model_id:
  desc: null
  value: finetuner_large_1_fp_1
models_dir:
  desc: null
  value: /Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/trained_models/Zheming/
load_data:
  desc: null
  value: true
source:
  desc: null
  value: large
network_type:
  desc: null
  value: large
iterations:
  desc: null
  value: 5
num_classes:
  desc: null
  value: 72
sigmoid_params:
  desc: null
  value:
  - - 1000
    - 1000
  - - 10000
    - 2000
  - - 100000
    - 5000
batch_size:
  desc: null
  value: 230
lr:
  desc: null
  value: 0.002597
enable_logging:
  desc: null
  value: true
wandb_project_id:
  desc: null
  value: exp_finetuner_fp
num_hidden_layers:
  desc: null
  value: 2
num_neurons:
  desc: null
  value: 742
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719097825
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.17.0
      6: 4.29.2
      8:
      - 5
      - 13
      13: darwin-arm64
