wandb_version: 1

data_id:
  desc: null
  value: datasets/detector
model_name:
  desc: null
  value: nummutnet
iterations:
  desc: null
  value: 2000
batch_size:
  desc: null
  value: 200
lr:
  desc: null
  value: 0.0001
enable_logging:
  desc: null
  value: true
wandb_project_id:
  desc: null
  value: nummutnet
num_hidden_layers:
  desc: null
  value: 1
num_neurons:
  desc: null
  value: 5000
device:
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717102964
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.17.0
      6: 4.29.2
      8:
      - 5
      - 13
      13: darwin-arm64
