config:
    # IDs & paths
    data_id: "real_data"
    model_id: "generator"
    models_dir: "/Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/trained_models/"
    cosmic_version: "v3"
    type: "real"

    # Training params
    iterations: 100
    num_classes: 72
    lagrange_param: 0.001
    batch_size: 100
    lr_encoder: 0.005
    lr_decoder: 0.0005

    # WANDB params
    enable_logging: True
    wandb_project_id: "fix_generator_oversample"

    # Network params
    num_hidden_layers: 5
    latent_dim: 100

    # Misc
    device: "cuda"